apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-app-deployment
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-app
  template:
    metadata:
      labels:
        app: echo-app
    spec:
      containers:
      - name: echo-container
        image: yarodash/test-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8000
        volumeMounts:
          - name: echo-app-pvc
            mountPath: /app/mount-test-dir
      volumes:
        - name: echo-app-pvc
          persistentVolumeClaim:
            claimName: volume-claim
