apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
  namespace: dev
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ssd
  hostPath:
    path: "/data/"
